### ISSUE TITLE
This is NOT issue BUT need TXID FULL

### ISSUE THREAD

**Issue by edudiy** [zertrin/clikraken#37]
Hello, excellent program !!

`clikraken place sell -t market 0.10001`   or   `clikraken place buy -t market 0.10001`

and the output is:

```
sell 0.10001000 LTCEUR @ market
OB3PSH-PFSXO-6MCFPZ
```

![imagen](https://user-images.githubusercontent.com/29524734/102704335-fd19db80-4271-11eb-8f47-d478256b7344.png)

I need full trade info !!

This:

```
txid;time;pair;type;ordertype;vol;price;cost;fee;margin;ordertxid;misc
TA3SLG-BR4EU-7X7WU7;2020-12-19 21:20:05+00:00;XLTCZEUR;sell;market;0.10001000;99.51995;9.95299;0.01990;0.00000;OB3PSH-PFSXO-6MCFPZ;
```

I want launch this:

`clikraken place sell -t market 0.10001`     and output in the file:   OB3PSH-PFSXO-6MCFPZ.txt    or add to my file with all trades: trades_full.txt   ( after with grep I can search this "OB3PSH-PFSXO-6MCFPZ" in trades_full.txt and select only this line )

In BASH I undestand but in python am a fisher man.

Do you helpme that file must change o modify in clikraken for only add full trade in file txt ¿?

It´s is important for fee, final value of operation, ticket of kraken that is as show in WEB of Kraken not for Id OP ( OB3PSH-PFSXO-6MCFPZ ).

I tried this in file "place_order.py", but nothing:

![imagen](https://user-images.githubusercontent.com/29524734/102704344-1de23100-4272-11eb-8e4d-de3ec25d01a5.png)

Thanks for this GREAT program !! EXCELLENT

**Comment by zertrin** [comment]
Thanks for asking. Note that I am not maintaining this tool anymore, as I have stopped trading cryptocurrencies myself.

What you would like is not really possible, because this information is not available from response data given by the Kraken API when placing a trade.

See https://www.kraken.com/features/api#add-standard-order

And notice that the return is only:

```
descr = order description info
    order = order description
    close = conditional close order description (if conditional close set)
txid = array of transaction ids for order (if order was added successfully)
```

Which is exactly the data that clikraken returns to the user. There is no more data to show after placing an order.

Do note that when placing an *order*, the *trade* has not really been done yet (even if the order type is market). The trade happens *after* the order is submitted. This is why the _Place Order API_ cannot return any information about the trade itself (such as fee, cost, ...).

Additional information about trades is only available by using the `TradesHistory` API or `QueryTrades` API, which is available using `clikraken --csv trades`.

```
usage: clikraken trades [-h] [-t TYPE] [-s START] [-e END] [-o OFS] [-i ID]
                        [-p PAIR]

optional arguments:
  -h, --help            show this help message and exit
  -t TYPE, --type TYPE  type of trade. Values: all|any position|closed
                        position|closing position|no position (default: all)
  -s START, --start START
                        starting unix timestamp or trade tx id of results
                        (exclusive) (default: None)
  -e END, --end END     ending unix timestamp or trade tx id of results
                        (exclusive) (default: None)
  -o OFS, --ofs OFS     result offset (default: None)
  -i ID, --id ID        comma delimited list of transaction ids to query info
                        about (20 maximum) (default: None)
  -p PAIR, --pair PAIR  asset pair (default: None)
```

**Comment by zertrin** [comment]
Note also that a trade ID (starting with `T`) and an order ID (starting with `O`) are different things.

One order ID can generate more than one trade (because sometimes it is not possible to fill the order with only one trade, so the order is filled in multiple trades).

Consequently, you need to figure out which trades belong to which order using the trade history. This logic can be implemented by the user and is not in the scope of clikraken (which is just an API client for Kraken.com)

**Comment by edudiy** [comment]
Ok, thks for response & all.

I test:

clikraken trades --i TA3SLG-BR4EU-7X7WU7    and the result is excellent, all info because I have Trade ID.

But, when an operation launch the exit is:  Order ID

Do exist any form to search for Order ID and locate the rest of the all info ?

txid                 time                       pair      type    ordertype        vol     price     cost     fee    margin  ordertxid            misc
-------------------  -------------------------  --------  ------  -----------  -------  --------  -------  ------  --------  -------------------  ------
TA3SLG-BR4EU-7X7WU7  2020-12-19 21:20:05+00:00  XLTCZEUR  sell    market       0.10001  99.51995  9.95299  0.0199         0  OB3PSH-PFSXO-6MCFPZ

I have a BOT in BASH with implemented searching of TRADES ID, but any times, are more than 50 Operations and when the BOT launch:

clikraken --csv trades > id_op_trades.txt

This Trade is NOT, is more older than 50 last operations.


Do exist any form to search for Order ID and locate the rest of the all info ?



Thank your so much !!

**Comment by zertrin** [comment]
Only from the ledgers or trade history. You need to query more data from the API if you have many trades. Look at start and end options shown above.

**Comment by edudiy** [comment]
Ok, thks !!

Now I can search for TIME STAMP, it's excellent !!

How can I see the VOLUME with clikraken ?

$371,406.87 / $500,000 (74.28%)

And it´s possible the rest of info of VOLUME as view via WEB of Kraken:

0.10 0.20%   Tarifa actual ( Fee NOW )

$371,406.87 / $500,000 (74.28%)

0.08 0.18%   Siguiente Tarifa ( Next Fee )

![imagen](https://user-images.githubusercontent.com/29524734/103223241-b422f080-491d-11eb-9dd2-481473f9d4f3.png)

Thanks allways !!

**Comment by zertrin** [comment]
Sorry but not all API endpoints have been implemented in clikraken.

For reference, I have now added the list of supported API endpoints to the README:
https://github.com/zertrin/clikraken/blob/master/README.md#list-of-supported-kraken-api-endpoints

As mentioned earlier, I do not maintain this tool anymore, but since it's open source, anyone can fork it and implement additional features if they wish so.

I suspect the `TradeVolume` API (https://www.kraken.com/features/api#get-trade-volume) isn't hard to implement.

**Comment by edudiy** [comment]
Thks for your CLIENT & your responses !!

I have a new problem than don´t understand...

![imagen](https://user-images.githubusercontent.com/29524734/106403424-979b3c00-6426-11eb-9b70-9790ddd90646.png)

This problem it´s new for me, ...the orders in market not execute and shown this message.

I search and don't see it

**Comment by zertrin** [comment]
Sorry, this is an error directly from Kraken API. You should contact Kraken support instead.
