### ISSUE TITLE
clikraken ticker Error from 31 Jan of 2024 by changes of Kraken ( must use GET not POST )

### ISSUE THREAD

**Issue by edudiy** [zertrin/clikraken#43]
Hello

From 31 Jan of 2024 Kraken **clikraken ticker** show error:

![imagen](https://github.com/zertrin/clikraken/assets/29524734/5d13fa5f-2eac-4cf6-aaa1-babfd71bbbf5)

Launching **clikraken ticker**

![imagen](https://github.com/zertrin/clikraken/assets/29524734/f6d5707c-d6cd-4b91-80ec-629474268bcd)

Anybody can update the command: **ticker** ?

Thanks for all !!

**Comment by zertrin** [comment]
Hum, would need to update the [krakenex](https://github.com/veox/python3-krakenex) dependency. (clikraken delegates the calls to Kraken's API to that library)

I see that [they have recently released an update](https://github.com/veox/python3-krakenex/blob/master/CHANGELOG.rst) regarding the removal of POST for public APIs (in versions 2.2.0 and 2.2.1).

~~You can probably solve the issue locally yourself by updating krakenex in your virtual environment: `pip install -U krakenex`~~

Edit: this probably won't work. I just noticed clikraken still uses krakenex version `0.1.4` (based on restricting the version to `krakenex>=0.1,<1.0`). [Version 1.0 introduced breaking API changes](https://github.com/veox/python3-krakenex/blob/master/CHANGELOG.rst#v100---2017-09-18-monday), which means some extra work will probably be needed to make clikraken use it. But even then, there's still [version 2.0 to adapt to, with more breaking changes](https://github.com/veox/python3-krakenex/blob/master/CHANGELOG.rst#v100---2017-09-18-monday).

I will have a look tomorrow whether the upgrade path is easy or not. If it's not, then someone else will need to look into it and open a contribution PR (since [I don't maintain this project anymore](https://github.com/zertrin/clikraken/issues/35))

**Comment by zertrin** [comment]
Okay, so I just went ahead and updated the krakenex dependency, since actually clikraken wasn't directly affected by the breaking changes.

It's released as version 0.8.5.

You can upgrade with `pip install clikraken -U` and check `clikraken --version` for `0.8.5`

**Comment by zertrin** [comment]
Closing as there was no more issue feedback since the released fix.

**Comment by edudiy** [comment]
Thanks for your quick response for resolve the fix.

**Comment by edudiy** [comment]
I have 2 ways for new changes from Kraken, I add the code of my proyect. Anybody can select price of Clikraken or direct link to Kraken and write in files as registries or only view in screen.

This create 2 files:

- 1 price in 1 line ( current, max24h, min24h ) in 1 file .txt  ( /home/pi/LTCEUR_only_current_price.txt )
- cronology prices each 3 sg perfect for graphs in 1 file .txt ( /home/pi/LTCEUR_prices.txt )


Folder main:  /home/pi/
Subfolder: /home/pi/disi_multiu_dev2_coloker_do/
Folder of Script: /home/pi/disi_multiu_dev2_coloker_do/ticker/getprice.sh

Script in BASH for Litecoin / Euro:

```bash
#!/bin/bash
{

ruta=`pwd`

ruta2='/home/pi/disi_multiu_dev2_coloker_do'

export CLIKRAKEN_API_KEYFILE=$ruta/kraken.key
export CLIKRAKEN_USER_SETTINGS_PATH=$ruta/kraken_settings.ini

# ========== INICIO de BUCLE PROGRAMA =============

while true
do

clear

echo
echo
echo
echo

date

mode_value=`cat $ruta2/mode_value.txt`		# mode_value=1  usa Clikraken   # mode_value=0   no usa Clikraken

if [ $mode_value -eq 1 ]
then
	
	clikraken --csv ticker > $ruta/valores.txt
	
	echo
	echo

	fecha=`date +"%H:%M:%S;%d/%m/%Y"`

	echo
	echo

	linea_full=`tail -1 $ruta/valores.txt`

	valor=`echo "$linea_full" | cut -d\; -f2 | head -1`
	max24=`echo "$linea_full" | cut -d\; -f3 | head -1`
	min24=`echo "$linea_full" | cut -d\; -f4 | head -1`
	
	valor=`echo "scale=2; $valor/1" | bc`
	max24=`echo "scale=2; $max24/1" | bc`
	min24=`echo "scale=2; $min24/1" | bc`
	
	cliente='Usa Clikraken'
	
else

	curl -s -X GET https://api.kraken.com/0/public/Ticker?pair=LTCEUR > $ruta/valores.txt

	echo
	echo

	fecha=`date +"%H:%M:%S;%d/%m/%Y"`

	echo
	echo

	valor=`cat $ruta/valores.txt | jq '.result[] | .c[0]' | sed -e 's/\"//g'`
	max24=`cat $ruta/valores.txt | jq '.result[] | .h[0]' | sed -e 's/\"//g'`
	min24=`cat $ruta/valores.txt | jq '.result[] | .l[0]' | sed -e 's/\"//g'`

	valor=`echo "scale=2; $valor/1" | bc`
	max24=`echo "scale=2; $max24/1" | bc`
	min24=`echo "scale=2; $min24/1" | bc`
	
	cliente='No usa Clikraken'

fi


stop8=`cat $ruta2/stop8.txt`     # If 1 IN, if other OUT

if [ $stop8 -eq 1 ]     # Select write in file or only view in screen
then

	echo "$valor - $fecha - MAX: $max24 - MIN: $min24 | $cliente"
	
	echo "$valor;$fecha;$max24;$min24;" >> /home/pi/LTCEUR_prices.txt

	echo "$valor;" > /home/pi/LTCEUR_only_current_price.txt

else

	echo "$valor - $fecha - MAX: $max24 - MIN: $min24 | $cliente	 ( STOP8 - NO escribe valor SOLO muestra )"

fi

# =========== Obtención de datos FINALIZADA ======================

echo
echo

sleep 3


done

}
```
