### ISSUE TITLE
4-letter asset pairs aren't correctly displayed

### ISSUE THREAD

**Issue by t0neg** [zertrin/clikraken#7]
Hi,

Taking DASH as example:
Command:
```
PS D:\> clikraken t -p DASHEUR
pair       last    high      low      vol     wavg  vol value        ask      bid
------  -------  ------  -------  -------  -------  -----------  -------  -------
ASHUR   85.9693   86.98  78.5176  3737.62  82.4414  308 kHUR     86.7469  85.9693
```

**Comment by havocesp** [comment]
Have yout tried ASHEUR?

**Comment by zertrin** [comment]
There is no easy solution here... I initially assumed that all pairs in long form from Kraken were in the form `(X|Z)AAA(X|Z)BBB` with AAA and BBB are the 3-letter asset names.... But of course there need to be an exception now...

One the one hand I'm unwilling to hard-code a list of pairs in clikraken since they change often. On the other hand, without prior knowledge of the informations returned by the AssetPairs API call, it's hard to handle things consistently.

One idea would be to cache that information locally, but that implies some sort of persistent storage enabled by default, which I'm reluctant to do. I don't want clikraken to write files by itself. Until now I leave the responsibility to write files to the user instead (this choice solves a whole class of potential issues related to file writing (correct and expected location, correct filesystem permissions, acceptance from the user and so on...)).

Another not so appealing solution would be to stop using short versions of the asset pais everywhere in the code and exclusively ust the full version. But that's pretty user-unfriendly too...

Any other ideas?

**Comment by zertrin** [comment]
With the workaround proposed by @t0neg in PR #9 I'll consider this issue closed since I couldn't come with a better idea. Until next exception or if a better idea surfaces... :-)
